name: my_dbt_project
version: '1.0'
config-version: 2

profile: my_dbt_project

model-paths: ["models"]
macro-paths: ["macros"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  staging:
    materialized: view