version: 2

models:
  - name: srv_properties
    description: "A serving model for properties"
    columns:
      - name: url
        description: "The URL of the property listing"
        data_tests:
          - not_null

      - name: address
        description: "The address of the property listing"
        data_tests:
          - not_null

      - name: postcode
        description: "The postcode of the property"
        data_tests:
          - not_null
    tests:
      - dbt_utils.unique_combination_of_columns:      # Unique combination of columns Agent Name and Agent URL
          combination_of_columns: ['agent_name', 'agent_url']
      - dbt_utils.unique_combination_of_columns:     # Unique combination of columns URL and Date the property is added 
          combination_of_columns: ['url', 'added']
      - dbt_utils.expression_is_true:       # Ensure that the price is non-negative 
          expression: "price >= 0"

  - name: dim_agents
    description: "A serving model for agents"
    columns:
      - name: agent_name
        description: "The name of the agent"
        data_tests:
          - not_null

      - name: agent_address
        description: "The address of the agent"
        data_tests:
          - not_null

      - name: agent_url
        description: "The URL of the agent's profile"
        data_tests:
          - not_null
    tests:
      - dbt_utils.unique_combination_of_columns: # Unique combination of columns Agent Name, Agent URL, and Agent Address
          combination_of_columns: ['agent_name', 'agent_url','agent_address'] 